# Generated by Django 3.2.6 on 2021-08-16 08:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0002_auto_20210816_0718'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserRecipes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=120)),
                ('link', models.URLField()),
            ],
        ),
        migrations.AddField(
            model_name='userprofile',
            name='recipes',
            field=models.ManyToManyField(blank=True, to='pages.UserRecipes'),
        ),
    ]
